/**
 * Phase G G3: deployment template emitter.
 *
 * Produces the files in `architecture/DEPLOYMENT_TEMPLATE/` that wire the
 * research-driven schema into a real database + auth provider + hosting
 * target. The template is opinionated: Supabase Postgres + Vercel + Resend
 * (or mocked email). Agents that want a different stack should diverge in
 * `BUILD_LOG.md` (see `docs/BUILD_RECIPE.md`).
 *
 * Inputs: ResearchExtractions (for env vars from integrations.json) and
 * the workspace's `architecture/DATABASE_SCHEMA.sql` content.
 *
 * Outputs (all paths relative to package root):
 *   - architecture/DEPLOYMENT_TEMPLATE/supabase/migrations/0001_init.sql
 *   - architecture/DEPLOYMENT_TEMPLATE/next.config.mjs
 *   - architecture/DEPLOYMENT_TEMPLATE/.env.template
 *   - architecture/DEPLOYMENT_TEMPLATE/vercel.json
 *   - architecture/DEPLOYMENT_TEMPLATE/Makefile
 *   - architecture/DEPLOYMENT_README.md (top-level inside the template dir)
 */
import type { ResearchExtractions } from '../research/schema';

export type DeploymentTemplateFile = { path: string; content: string };

const TEMPLATE_ROOT = 'architecture/DEPLOYMENT_TEMPLATE';

function buildSupabaseMigration(databaseSchemaSql: string): string {
  // The DDL emitted by lib/generator/database-schema.ts is already PostgreSQL
  // flavored; we add a Supabase-correct preamble that enables row-level
  // security skeletons and pins the search_path.
  return `-- Supabase migration: 0001_init.sql
-- Generated from architecture/DATABASE_SCHEMA.sql.
-- Apply with:  supabase db push  OR  psql $DATABASE_URL -f 0001_init.sql

-- Postgres preamble: pin search_path and enable extensions Supabase users
-- typically expect. Drop the extension lines if you're targeting plain
-- Postgres without Supabase.
SET statement_timeout = 0;
SET lock_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SET search_path = public;

-- Optional: enable uuid_generate_v4() if any table uses it as a default.
-- Comment out if your schema uses gen_random_uuid() (pgcrypto) or app-side IDs.
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

${databaseSchemaSql.trim()}

-- Row-level security scaffolding (uncomment per table once policies are written):
-- ALTER TABLE <table> ENABLE ROW LEVEL SECURITY;
-- CREATE POLICY <name> ON <table> FOR SELECT USING (auth.uid() IS NOT NULL);
`;
}

function buildNextConfig(): string {
  return `/**
 * next.config.mjs — generated by mvp-builder G3 deployment template.
 * Standard Next.js 14 (app router) configuration with the few production
 * defaults a Vercel deployment expects.
 */
/** @type {import('next').NextConfig} */
const nextConfig = {
  reactStrictMode: true,
  poweredByHeader: false,
  experimental: {
    // Server actions are GA in Next.js 14 but explicit here for clarity.
    serverActions: { bodySizeLimit: '2mb' }
  },
  // Add image domains here once integrations.json declares an image CDN.
  images: { remotePatterns: [] }
};

export default nextConfig;
`;
}

function buildEnvTemplate(ex: ResearchExtractions | undefined): string {
  const lines: string[] = [];
  lines.push('# .env.template — generated by mvp-builder G3.');
  lines.push('# Copy to .env.local and fill in real values for development.');
  lines.push('# NEVER commit .env.local; the template is the only file in version control.');
  lines.push('');
  lines.push('# --- Database (Supabase Postgres) ---');
  lines.push('# Connection pool string for application code:');
  lines.push('DATABASE_URL=postgres://postgres:<password>@<project>.pooler.supabase.com:6543/postgres');
  lines.push('# Direct connection for migrations:');
  lines.push('DIRECT_URL=postgres://postgres:<password>@db.<project>.supabase.co:5432/postgres');
  lines.push('# Anon key for client-side Supabase calls (only if you use Supabase JS):');
  lines.push('NEXT_PUBLIC_SUPABASE_URL=https://<project>.supabase.co');
  lines.push('NEXT_PUBLIC_SUPABASE_ANON_KEY=<anon-key>');
  lines.push('');
  lines.push('# --- Auth (magic-link via Resend) ---');
  lines.push('RESEND_API_KEY=re_<...>');
  lines.push('AUTH_FROM_EMAIL=hello@example.com');
  lines.push('AUTH_MAGIC_LINK_PROVIDER=resend  # set to "mock" in dev to write links to a local file');
  lines.push('AUTH_SESSION_SECRET=<openssl rand -hex 32>');
  lines.push('');
  lines.push('# --- Hosting (Vercel) ---');
  lines.push('# These are auto-injected by Vercel in production; only set locally for testing.');
  lines.push('# VERCEL_URL=');
  lines.push('# VERCEL_ENV=development');
  lines.push('');
  lines.push('# --- App ---');
  lines.push('NEXT_PUBLIC_APP_URL=http://localhost:3000');
  if (ex && ex.integrations && ex.integrations.length) {
    lines.push('');
    lines.push('# --- Researched integrations ---');
    lines.push('# These env vars come from research/extracted/integrations.json. Required vars are uncommented;');
    lines.push('# optional ones are commented. Mocked-by-default integrations have a "MOCK_*" toggle.');
    const seen = new Set<string>();
    for (const integ of ex.integrations) {
      if (!integ.envVar || seen.has(integ.envVar)) continue;
      seen.add(integ.envVar);
      lines.push('');
      lines.push(`# ${integ.name} (${integ.vendor}, ${integ.category}) — ${integ.purpose}`);
      const prefix = integ.required ? '' : '# ';
      lines.push(`${prefix}${integ.envVar}=`);
      if (integ.mockedByDefault) {
        const mockVar = `MOCK_${integ.envVar.replace(/[^A-Z0-9_]/g, '_')}`;
        lines.push(`# Set ${mockVar}=true in dev to skip the real provider:`);
        lines.push(`# ${mockVar}=true`);
      }
    }
  }
  return lines.join('\n') + '\n';
}

function buildVercelJson(): string {
  // Minimal vercel.json. Most settings are auto-detected; the items below
  // protect against common production foot-guns.
  const config = {
    $schema: 'https://openapi.vercel.sh/vercel.json',
    framework: 'nextjs',
    buildCommand: 'npm run build',
    devCommand: 'npm run dev',
    installCommand: 'npm install',
    regions: ['iad1'],
    functions: {
      'app/api/**/*.ts': { maxDuration: 30 }
    },
    headers: [
      {
        source: '/(.*)',
        headers: [
          { key: 'X-Content-Type-Options', value: 'nosniff' },
          { key: 'Referrer-Policy', value: 'strict-origin-when-cross-origin' },
          { key: 'X-Frame-Options', value: 'DENY' }
        ]
      }
    ]
  };
  return JSON.stringify(config, null, 2) + '\n';
}

function buildMakefile(): string {
  // Tabs are mandatory in Makefile recipe lines.
  return `# Makefile — generated by mvp-builder G3 deployment template.
# One-shot deployment + database lifecycle commands. Requires the Supabase
# CLI (\`supabase\`) and Vercel CLI (\`vercel\`) installed and authenticated.

.PHONY: help install migrate seed deploy smoke rollback

help:
\t@echo "Targets:"
\t@echo "  make install   — install npm deps + supabase + vercel CLIs (idempotent)"
\t@echo "  make migrate   — apply Supabase migrations (0001_init.sql)"
\t@echo "  make seed      — load SAMPLE_DATA.md fixtures into the dev database"
\t@echo "  make deploy    — vercel --prod (idempotent; uses .env from Vercel)"
\t@echo "  make smoke     — hit deployed URL's health endpoint + run Playwright suite"
\t@echo "  make rollback  — vercel rollback to previous deployment"

install:
\tnpm install
\t@command -v supabase >/dev/null 2>&1 || (echo 'install supabase CLI: https://supabase.com/docs/guides/cli' && exit 1)
\t@command -v vercel >/dev/null 2>&1 || npm install -g vercel

migrate:
\tsupabase db push --include-all || (echo 'migrate failed; ensure DIRECT_URL is set and the project is linked' && exit 1)

seed:
\t@echo 'Apply SAMPLE_DATA.md fixtures (implementation-specific; see DEPLOYMENT_README.md).'

deploy:
\tvercel --prod --yes

smoke:
\t@test -n "$$DEPLOY_URL" || (echo 'set DEPLOY_URL=https://<your-app>.vercel.app first' && exit 1)
\tcurl -fsS "$$DEPLOY_URL/api/health" >/dev/null && echo 'health ok'
\tnpx playwright test --reporter=line

rollback:
\tvercel rollback --yes
`;
}

function buildDeploymentReadme(ex: ResearchExtractions | undefined, productName: string): string {
  const integLines = ex?.integrations?.length
    ? ex.integrations
        .filter((i) => i.required)
        .map((i) => `  - **${i.name}** (\`${i.envVar}\`) — ${i.purpose}`)
        .join('\n')
    : '  - none researched';
  return `# DEPLOYMENT_README

## What this is
A one-shot deployment scaffold for **${productName}** that wires the
research-driven schema into a real database + auth provider + hosting target.

The defaults are: **Supabase Postgres + Vercel + Resend (magic-link) + Next.js 14**.
If your build recipe pivots to a different stack, document the deviation in
\`BUILD_LOG.md\` (see \`docs/BUILD_RECIPE.md\`).

## Prerequisites
1. A Supabase project (free tier works for v1).
2. A Vercel account linked to your GitHub repo.
3. A Resend account with a verified sender domain (or use \`AUTH_MAGIC_LINK_PROVIDER=mock\` for local dev).
4. \`supabase\` CLI installed (\`brew install supabase/tap/supabase\` or equivalent).
5. \`vercel\` CLI installed (\`npm i -g vercel\`).

## One-shot deploy
\`\`\`bash
cp .env.template .env.local      # fill in DATABASE_URL, RESEND_API_KEY, etc.
make install                     # idempotent dep + CLI install
make migrate                     # apply 0001_init.sql to Supabase
make deploy                      # vercel --prod
DEPLOY_URL=https://your-app.vercel.app make smoke
\`\`\`

## Manual deploy
1. **Provision Supabase**: create a project, copy DATABASE_URL + DIRECT_URL into Vercel env.
2. **Apply migration**: \`psql $DATABASE_URL -f supabase/migrations/0001_init.sql\` (or \`supabase db push\`).
3. **Set Vercel env vars** (Settings → Environment Variables):
${integLines}
4. **Deploy**: \`npx vercel --prod\`.
5. **Smoke**: hit \`/api/health\` (returns 200 OK if DB connection works); run the Playwright suite in CI.

## Verifying the deployment
- \`/api/health\` returns 200 + JSON \`{ ok: true, db: true }\` from a fresh deployment.
- Sign-in flow: request a magic link, confirm email arrives (or check the mocked file in dev), click through to authenticated route.
- Database: \`SELECT count(*) FROM <one of your researched entities>;\` returns a row count.
- Each \`workflow.id\` from \`research/extracted/workflows.json\` has a corresponding route in the deployed app (e.g. \`/intake\`, \`/research\`, \`/prioritize\`).

## Rollback (if migration fails)
1. \`make rollback\` — Vercel rolls back to the previous green deployment.
2. **Database rollback**: there is no automatic \`down\` migration in 0001_init.sql. If the migration left the DB in a bad state:
   - For **destructive failure** (table created but constraint failed): \`psql $DATABASE_URL -c "DROP TABLE IF EXISTS <table> CASCADE;"\`
   - For **non-destructive failure** (transaction rolled back): no action needed.
   - Future migrations should ship with explicit \`down\` SQL alongside.

## Production smoke
After every deploy:
- The Playwright suite (one scenario per \`workflow.id\` happy-path + one per researched failure mode — see \`docs/BUILD_RECIPE.md\` pass B8) runs against \`$DEPLOY_URL\`.
- \`make smoke\` is the local entry point; CI runs the same suite via \`npx playwright test\`.

## What this template does NOT include
- Multi-region deployment.
- Background workers / queues (use Vercel Cron or Supabase Edge Functions if needed; researched integrations.json should declare them).
- Custom domain setup (Vercel dashboard).
- DNS / SSL config (Vercel handles automatically for vercel.app subdomains).
- Logging / observability beyond Vercel's defaults (add Sentry / Logtail when integrations.json declares them).

## Why this stack
- **Next.js 14 (app router)**: server actions + RSC let one route group serve a workflow without a separate API.
- **Supabase Postgres**: managed Postgres with built-in row-level security; the DDL we generate runs unmodified.
- **Vercel**: zero-config Next.js deploys; preview environments per PR.
- **Resend (or mock)**: cheap magic-link email; mock provider writes links to a file in dev so no API key is needed for local builds.

## Where each file fits
| File | Purpose |
|---|---|
| \`supabase/migrations/0001_init.sql\` | The first DB migration. Re-runs the workspace's DDL with a Supabase-correct preamble. |
| \`next.config.mjs\` | Next.js 14 production defaults. |
| \`.env.template\` | Every env var the deployed app needs. Required vs optional vs mocked is documented inline. |
| \`vercel.json\` | Per-route function timeouts + security headers. |
| \`Makefile\` | One-shot \`make deploy\` + lifecycle targets. |

## See also
- \`docs/BUILD_RECIPE.md\` — the 9-pass spec a coding agent executes to turn the workspace into a deployed app.
- \`architecture/DATABASE_SCHEMA.sql\` — the source of truth for the schema this migration applies.
- \`integrations/EXTERNAL_SERVICES.md\` — researched third-party services and their failure modes.
`;
}

export function renderDeploymentTemplate(args: {
  productName: string;
  databaseSchemaSql: string;
  extractions?: ResearchExtractions;
}): DeploymentTemplateFile[] {
  const { productName, databaseSchemaSql, extractions } = args;
  return [
    {
      path: `${TEMPLATE_ROOT}/supabase/migrations/0001_init.sql`,
      content: buildSupabaseMigration(databaseSchemaSql)
    },
    {
      path: `${TEMPLATE_ROOT}/next.config.mjs`,
      content: buildNextConfig()
    },
    {
      path: `${TEMPLATE_ROOT}/.env.template`,
      content: buildEnvTemplate(extractions)
    },
    {
      path: `${TEMPLATE_ROOT}/vercel.json`,
      content: buildVercelJson()
    },
    {
      path: `${TEMPLATE_ROOT}/Makefile`,
      content: buildMakefile()
    },
    {
      path: `${TEMPLATE_ROOT}/DEPLOYMENT_README.md`,
      content: buildDeploymentReadme(extractions, productName)
    }
  ];
}
