/**
 * Generate product-strategy/IDEA_CRITIQUE.md from research extractions.
 * Sources: meta.discovery.ideaCritique + meta.discovery.competingAlternatives
 *          + meta.researcher (the audit credits real critique only when
 *          the researcher is not the synthesizer).
 *
 * Phase E4 audit dimension `idea-clarity` rewards non-empty critique when
 * researcher !== 'mock'.
 */
import type { ResearchExtractions } from '../research/schema';

export function renderIdeaCritiqueMarkdown(ex: ResearchExtractions): string {
  const critique = ex.meta.discovery?.ideaCritique ?? [];
  const alternatives = ex.meta.discovery?.competingAlternatives ?? [];
  const isSynth = ex.meta.researcher === 'mock';

  const critiqueBlock = critique.length
    ? critique
        .map((c, i) => `### Weak spot ${i + 1}

- **What's risky:** ${c.weakSpot}
- **How to mitigate:** ${c.mitigation}`)
        .join('\n\n')
    : isSynth
      ? `_The synthesizer does not produce idea critique by design — it only templates from the brief and would generate hollow text here. Run the recipe (Pass 0) inside an LLM-driven agent to populate this section honestly._`
      : `_No idea-critique points extracted. Either the brief is unusually airtight or Pass 0 needs another iteration._`;

  const alternativesBlock = alternatives.length
    ? alternatives
        .map(
          (a, i) =>
            `### Alternative ${i + 1}: ${a.name}

- Why insufficient: ${a.whyInsufficient}`
        )
        .join('\n\n')
    : isSynth
      ? `_Synthesizer placeholder — populate via Pass 0 in the recipe._`
      : `_No competing alternatives recorded. Verify before claiming "no good options exist."_`;

  const synthBanner = isSynth
    ? `\n> ℹ️ This file was generated by the deterministic synthesizer (\`meta.researcher === 'mock'\`). The critique and alternatives sections are intentionally thin — they require an LLM agent to do the actual brief-challenging work. The audit's \`idea-clarity\` dimension does not credit synthesized critique.\n`
    : '';

  return `# IDEA_CRITIQUE
${synthBanner}
> Generated from research extractions. The point of this file is to surface weak spots in the brief itself — before phase work begins — and to record how each weak spot will be mitigated. Do not start phase 1 until every weak spot has either a mitigation plan or an explicit decision to accept the risk.

## Weak spots in the brief

${critiqueBlock}

## Competing alternatives the audience could choose instead

${alternativesBlock}

## Open questions for the human to answer before phase 1

- [ ] Is each weak spot above acknowledged with a decision (mitigate, accept, defer)?
- [ ] If "accept": is the failure mode it leaves open documented in \`requirements/REQUIREMENTS_RISK_REVIEW.md\`?
- [ ] If "defer": is the decision recorded with a date for revisitation?
- [ ] For each competing alternative: does our value proposition explain why it's not enough? If not, the value prop needs another iteration.
- [ ] Does the brief justify investment vs. the cheapest alternative (paper + spreadsheet)? If no, phase work is risky.
`;
}
